### ISSUE TITLE
Enable dataset writer to write hive partitioned parquet datasets

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#11500]
### Description

Enable dataset writer to write hive partitioned datasets (writing all / many destination files simultaneously).

**Comment by deanm0000** [comment]
and streaming from lazy...ya know, while you're at it.

**Comment by lmocsi** [comment]
This should be the other side of pl.scan_pyarrow_dataset (maybe pl.write_pyarrow_dataset).

**Comment by deanm0000** [comment]
`write_parquet` already takes arguments to use pyarrow dataset writer. See the example here https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.write_parquet.html.

**Comment by ion-elgreco** [comment]
> This should be the other side of pl.scan_pyarrow_dataset (maybe pl.write_pyarrow_dataset).

Can't you just do df.to_arrow() and then wrap it inside pyarrow.dataset.dataset?

**Comment by deanm0000** [comment]
> > This should be the other side of pl.scan_pyarrow_dataset (maybe pl.write_pyarrow_dataset).
> 
> Can't you just do df.to_arrow() and then wrap it inside pyarrow.dataset.dataset?

well that's what write_parquet does if you set those parameters. It can't stream though. So if you've got a lazyframe then you can't stream that into a dataset.

**Comment by deanm0000** [comment]
@uditrana you can use `df.write_parquet` with `use_pyarrow=True` and feed `pyarrow_options` with a dict where one key is `partition_cols`  https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.write_parquet.html#polars.DataFrame.write_parquet

**Comment by uditrana** [comment]
If I pass in additional kwargs (along with `partition_cols`) to `pyarrow_options`, then they should match the signature of `pyarrow.write_to_dataset` and not `pyarrow.write_to_table`, correct?

**Comment by deanm0000** [comment]
yup, it just uses `pyarrow.write_to_dataset` under the hood.

**Comment by ion-elgreco** [comment]
May I suggest to use delta-rs instead combind with https://github.com/delta-incubator/deltatorch

**Comment by jmakov** [comment]
> May I suggest to use delta-rs instead combined with [delta torch](https://github.com/delta-incubator/deltatorch)

Is streaming supported for `.scan_delta`?

**Comment by 29antonioac** [comment]
Hi, quick question, is the aim of this issue to not rely on pyarrow? I've found using pyarrow to write partitioned datasets can be memory intensive and I thought doing it in Rust side could be beneficial on low-memory systems.

Thanks for the hard work!

**Comment by lmocsi** [comment]
> yup, it just uses `pyarrow.write_to_dataset` under the hood.

Are you referring to ds.write_dataset()? If yes, then is has some drawbacks, too: https://github.com/apache/arrow/issues/39768

**Comment by deanm0000** [comment]
> Hi, quick question, is the aim of this issue to not rely on pyarrow? 


Yes

>I've found using pyarrow to write partitioned datasets can be memory intensive and I thought doing it in Rust side could be beneficial on low-memory systems.

Probably not, pyarrow is c and c++ so I wouldn't think it'd be materially different in memory usage than rust. It maybe implemented differently but it's not like pyarrow is implemented in pure Python.

**Comment by deanm0000** [comment]
Sink exclusively uses the streaming engine which doesn't yet support all possible operations. Unfortunately that means if it doesn't work there's nothing* you can do to make it work. 


*there are a few methods (undocumented) that aren't in the streaming engine that can be replicated with methods that are. Aggregations are generally not in that category so this probably doesn't apply for agg.

**Comment by Smotrov** [comment]
It there any option to make `sink_json` partitioned? Usually have huge datasets. 
If it could sink it to a cloud (AWS S3) it would be amazing.

**Comment by cmdlineluser** [comment]
@Smotrov I don't believe so.

Other formats are on the list in:

> Support Hive partitioning logic in other readers besides Parquet

- https://github.com/pola-rs/polars/issues/15441

Perhaps JSON can be added.

**Comment by nameexhaustion** [comment]
Fixed by https://github.com/pola-rs/polars/pull/17324
IPC support is tracked at https://github.com/pola-rs/polars/issues/17481

**Comment by EpicUsaMan** [comment]
> Support for writing hive partitioned parquet is added by #17324 IPC support is tracked at #17481

But sink_parquet still doesn't support hive partitioning which leads to two bottlenecks:
* compression in one thread
* not utilizing whole SSD while writing using sink_parquet

So could we reopen this or should I create new issue? Because I didn't find such

**Comment by lmocsi** [comment]
I guess you should create a new one, and reference this one there.

**Comment by EpicUsaMan** [comment]
> I guess you should create a new one, and reference this one there.

Maintainer said that it will be in polars 2.0
