### ISSUE TITLE
Filters sometime fill null string value with ""

### ISSUE THREAD

**Issue by potter420** [pola-rs/polars#1322]
#### Are you using Python or Rust?

 **Python**.

#### What version of polars are you using?

0.9.2, 0.9.3_beta1

#### What operating system are you using polars on?

Amazon Linux 2

#### Describe your bug.

Filters sometime fill null string value with ""

This seem to be arrow2 problems, since the result get from 0.9.3 which use main arrow packages is different.

#### What are the steps to reproduce the behavior?

```python
import polars as pl

a = pl.DataFrame({
    'd': ['u','u','d','c','c','d','d']*250,
    'v1': [None, 'help',None ,None,None,None, None]*250,
    'v2': [None, 'help',None ,None,None,None, None]*250,
    'v3': [None, 'help',None ,None,None,None, None]*250
})
print(a.filter(pl.col('d')!='d').select([
    pl.col('v1').unique()
]))
```

#### What is the actual behavior?

```
shape: (3, 1)
┌────────┐
│ v1     │
│ ---    │
│ str    │
╞════════╡
│ null   │
├╌╌╌╌╌╌╌╌┤
│ "help" │
├╌╌╌╌╌╌╌╌┤
│ ""     │
└────────┘
```

#### What is the expected behavior?

```
shape: (2, 1)
┌────────┐
│ v1     │
│ ---    │
│ str    │
╞════════╡
│ null   │
├╌╌╌╌╌╌╌╌┤
│ "help" │
└────────┘
```

**Comment by ritchie46** [comment]
I believe this is already fixed in 0.9.3!

**Comment by potter420** [comment]
Thanks, since in 0.9.3, I encounter other issue with this:
```
select([
    (pl.col('v1').shift(-1)=='help')|(pl.col('v1').shift(-1).is_null())
]))
PanicException: assertion failed: ceil(offset + len, 8) <= buffer.len() * 8
```

Which to me look like an old bugs.

**Comment by ritchie46** [comment]
Ah, thats an arrow-rs issue. Should be resolved now we're back on arrow2 again.

**Comment by potter420** [comment]
Hi @ritchie46, I still encounter this issue in polar 0.9.4 and 0.9.5_beta1.

**Comment by ritchie46** [comment]
@potter420 , I will investigate this.

**Comment by ritchie46** [comment]
Fixed in #1338. Thanks a lot @jorgecarleitao  for the swift response.

**Comment by ritchie46** [comment]
Fixed and being released at the moment: https://github.com/pola-rs/polars/pull/1339/checks?check_run_id=3569701202
