### ISSUE TITLE
`read_ipc` and `scan_ipc` use more memory than needed.

### ISSUE THREAD

**Issue by useredsa** [pola-rs/polars#17369]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Prepare a big file:
```python
import datetime as dt
import polars as pl

def MockupData(ts, num_rows):
  return pl.select(pl.lit(ts).alias('ts'), pl.arange(0, num_rows, eager=True).alias('val'))

if __name__ == '__main__':
  num_rows = 1 << 27 # For a df of 2 GB
  ts = dt.datetime(2024, 07, 1)
  df = MockupData(ts, num_rows)
  df.write_ipc('my_df', compression='zstd')
```

Then read the file and measure memory usage
```python
import resource
import polars as pl

if name == '__name__':
  # This does not use extra memory
  # df = pl.read_ipc('my_df', memory_map=False, use_pyarrow=True, rechunk=False)
  df = pl.read_ipc('my_df', memory_map=False, rechunk=False)

  max_mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1e6
  print("max_mem: {:.5f} GB".format(max_mem))
```

### Issue description

The bug is that peak memory usage is way above 2 GB, the size of the loaded data.

If you test for different file sizes, you'll see that it is something around 1.5 x the dataframe size for polars 1.0.0. For a previous version I no longer run (thus I don't know the version of pyarrow), 0.20.6, it was 2 x more. This bug is related to #3360, an old issue which was supposedly solved.

### Expected behavior

I would expect the memory usage to be equal to the file size plus some constant term.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             Linux-6.5.1-41-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
> I would expect the memory usage to be equal to the file size plus some constant term.

You are writing compressed data? Why would you expect the memory usage to be equal?

**Comment by useredsa** [comment]
> You are writing compressed data? Why would you expect the memory usage to be equal?
I'm not expecting it to be equal, there should be some constant overhead. But the overhead here is proportional to the dataframe size. Are we compressing in memory and only after writing? You can compress on-the-fly.

The implications of this is that to work with 64 GB dataframes you need a machine with 128 GB of RAM. Hence, it increases your costs considerably.

Nevertheless, the problem is there even with umcompressed files. Hence, it's maybe not related to that.

**Comment by kdn36** [comment]
Using a lazy plan using `scan_ipc` will limit memory usage.

Comparing
```python
#df = pl.read_ipc('my_df')
df = pl.scan_ipc('my_df').collect()
```

gives, before/after, using the 1.36.1 release build:
```
$  python tt_read_ipc.py
Could not memory_map compressed IPC file, defaulting to normal read. Toggle off 'memory_map' to silence this warning.
max_mem: 4.25909 GB

$  python tt_scan_ipc.py
max_mem: 2.34874 GB
```

**Comment by ramcasa** [comment]
I tried this on `v1.37.0` and I get the following numbers:

```
df_size: 2.00 GiB
max_mem: 4.26 GiB.
```

```
df_size: 4.00 GiB
max_mem: 8.46 GiB.
````

<details>
<summary>Script</summary>

```
import resource
import polars as pl

if __name__ == "__main__":
    # This does not use extra memory
    # df = pl.read_ipc('my_df', memory_map=False, use_pyarrow=True, rechunk=False)
    df = pl.read_ipc("my_df", memory_map=False, rechunk=False)

    max_mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1e6
    print(f"df_size: {df.estimated_size('gb'):.2f} GiB.")
    print(f"max_mem: {max_mem:.2f} GiB.")
```

</details>

If you use `pl.scan_ipc("my_df", rechunk=False).collect(engine="in-memory")` instead then you get the following
(the same result as for the streaming engine).

```
df_size: 4.00 GiB.
max_mem: 4.57 GiB
```

Hence, it does not seem to me like the issue is solved for `read_ipc`. It seems, as stated, that the additional memory is 2 x the dataframe size.

Besides, should `.read_ipc(...)` be worse than `.scan_ipc(...).collect(engine="in_memory")`? Why not replace the first internally by the second? (When `memory_map=False`.)

**Comment by kdn36** [comment]
Thanks. The issue is open (I don't think any one is claiming that the issue is solved). 

Some background: the 2x memory behavior is the result of (i) mmap'ing the underlying file, plus (ii) materializing the data into memory. It is not considered a bug, although we do want to enhance the memory consumption, which may imply that we move away from mmap.

**Comment by ramcasa** [comment]
> Thanks. The issue is open (I don't think any one is claiming that the issue is solved).

Sorry, I think my original message looked harsh. I just wanted to make clear that the issue is still there for `read_ipc`.

> Some background: the 2x memory behavior is the result of (i) mmap'ing the underlying file, plus (ii) materializing the data into memory.

Why can't the dataframe use the mmapped pages?
