### ISSUE TITLE
Severe memory issues with `rolling` and `group_by`

### ISSUE THREAD

**Issue by MariusMerkleQC** [pola-rs/polars#18525]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import datetime

import resource

N = 100_000

df = pl.DataFrame(
    data=[
        [datetime(2021, 1, 1, 20, 0, 0)] * N,
        ["a"] * N,
        [i for i in range(N)],
    ],
    schema={"timestamp": pl.Datetime, "category": pl.Utf8, "value": pl.Float64},
)

df_rolled_group_by = df.rolling(
    index_column="timestamp",
    period="5y",
    # group_by="category",
).agg(pl.col("value").mean().alias("cumulative_mean_by_category"))

peak_memory_gb = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / (2**30)

print(f"Peak memory in GB: {peak_memory_gb}")
```

### Issue description

When using `group_by` in the `rolling()` operation, memory consumption skyrockets, even for small data frames. When using `N=100_000`, the memory reaches the following peak:
- `group_by=None`: 0.18 GB
- `group_by="category"`: 18.01 GB

### Expected behavior

The peak memory when using `group_by=None` and `group_by="category"` should be similar.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            macOS-14.6.1-arm64-arm-64bit
Python:              3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:32:50) [Clang 16.0.6 ]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               4.2.2
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.6.1
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             3.1.5
pandas               2.2.2
pyarrow              15.0.2
pydantic             2.8.2
pyiceberg            <not installed>
sqlalchemy           2.0.32
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0
None
```

</details>

**Comment by natchi92** [comment]
Do we know what the underlying issue here ? Would be great to get this resolved :)

**Comment by tobiasdekker92** [comment]
I think exactly the same holds for the `merge_asof `function if you include the by argument. Would be nice to also take this implementation into account when solving this bug.

**Comment by tobiasdekker92** [comment]
Can you maybe also profile the issue when you cast the group by variable into a categorical variable?

**Comment by Chuck321123** [comment]
I dont get it, I get 0.2Gb. Is this fixed now as of 1.22.0?

**Comment by MariusMerkleQC** [comment]
> I dont get it, I get 0.2Gb. Is this fixed now as of 1.22.0?

Hm, I do not with 1.22.0. Are you sure that you commented out `# group_by="category"` above? @Chuck321123 @gillan-krishna

**Comment by gillan-krishna** [comment]
@MariusMerkleQC memory issue persists with 1.22.0, can confirm.

**Comment by gillan-krishna** [comment]
Rn I'm trying https://github.com/pola-rs/polars/issues/21132#issuecomment-2651192394 tip by @ritchie46 
Install jemalloc, followed by this to run above script.
`
LD_PRELOAD=/usr/local/lib/libjemalloc.so MALLOC_CONF="dirty_decay_ms:5000,muzzy_decay_ms:5000,background_thread:true,metadata_thp:auto" python pl_debug.py`

has not worked for me, the peak memory has stayed the same.

**Comment by cmdlineluser** [comment]
Just forwarding a reply from Ritchie:

> That seems a problem with the implementation, not jemalloc. Will put it on my stack.
> The dedicated expressions are better, I would recommend using them when you can, until we have rolling in our new streaming engine.

The expressions:

- https://docs.pola.rs/api/python/dev/search.html?q=rolling_+by

e.g. [`.rolling_mean_by()`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.rolling_mean_by.html#polars.Expr.rolling_mean_by)

```python
df.with_columns(
    pl.col("value").rolling_mean_by("timestamp", "5y").over("category")
)
```

@gillan-krishna Perhaps you can try the expressions if they are suitable for your use case.

**Comment by ritchie46** [comment]
This was a pathological memory explosion issue in the implemenation. This will be fixed in new release.

**Comment by gillan-krishna** [comment]
@ritchie46 does the new implementation v1.23.0 require the columns to be sorted in a different manner than before? I'm getting a 
`ComputeError: input data is not sorted `
for the same  implementation - sorted by column within group. 
Have tried removing duplicated inputs in the sorted column to make it strictly ascending, but still gives me the same error

**Comment by ritchie46** [comment]
Your data is sorted within the group? Got a repro? (I might know what it is, just want to be sure).

**Comment by mhhhsn** [comment]
I am also getting `ComputeError: input data is not sorted` after this was included in 1.23.0. This is the minimal example that throws this error for me

```python
import polars as pl

df = pl.DataFrame(
    {
        "n": [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10],
        "col1": ["A", "B"] * 11,
    }
)

print(df.rolling("n", period="1i", group_by="col1").agg())
```

**Comment by cmdlineluser** [comment]
I think https://github.com/pola-rs/polars/pull/21444 is where it is being fixed.

**Comment by ritchie46** [comment]
Yes, fixed in #21444
