### ISSUE TITLE
Ability to append to an existing directory of parquet files with new partitions (mode=append)

### ISSUE THREAD

**Issue by pascalwhoop** [pola-rs/polars#18750]
### Description

Hey. 
Spark has `mode=append` for writing parquet files. This is kind of useful, it just adds more partitions to the folder of an existing dataset. Great for writing in batches across multiple runs. 

How would you solve this in polars? I know adding data to an _existing_ parquet file is a whole different game but just adding more files should be fairly OK no? I suspect, just not overwriting / deleting the whole existing folder structure should do the trick.

**Comment by deanm0000** [comment]
It does seem nuts to me that it silently overwrites files https://github.com/pola-rs/polars/issues/18242.

**Comment by cceyda** [comment]
I think maybe this is solved because I was able to append just fine (as long as it is a **new** partition, haven't tested existing partition behaviour). 

Example code modified (from the linked issue):
```
df_a = pl.DataFrame(
    {
        'type': ['a','b'],
        'date': ['2024-08-15','2024-08-16'],
        'value': [68,70]
    }
)
df_a.write_parquet(f'./example_part.parquet', partition_by='date')
df_b = pl.DataFrame(
    {
        'type': ['a','b'],
        'date': ['2024-08-17','2024-08-18'],
        'value': [72,74]
    }
)
df_b.write_parquet(f'./example_part.parquet', partition_by='date')

pl.read_parquet(f'./example_part.parquet')

```
returns:
```

type | date | value
-- | -- | --
str | str | i64
"a" | "2024-08-15" | 68
"b" | "2024-08-16" | 70
"a" | "2024-08-17" | 72
"b" | "2024-08-18" | 74
```

**Comment by amitgilad3** [comment]
just tested it out and it still happens with latest version 1.14.0

**Comment by redfave** [comment]
> just tested it out and it still happens with latest version 1.14.0
Also as of version 1.18.0.
I really need the functionality to append to files, otherwise my workload is not processable as it doesn't fit into RAM and streaming is unfortunately not an option in my case.

**Comment by cceyda** [comment]
@redfave one work around I can recommend is adding a new column like "batch_id" & partitioning on that column while writing (You can partition by multiple columns too). Because **new partitions** do get added to an existing save  (Refer to the example above), so you can save as you are processing each batch.

**Comment by cjrh** [comment]
@pascalwhoop @redfave I think `use_pyarrow` does appends correctly:

```python
# main2.py
import polars as pl

kwargs = dict(
    use_pyarrow=True,
    pyarrow_options=dict(partition_cols=['type'])
)

df = pl.DataFrame(
    {
        'type': ['a','b'],
        'date': ['2024-08-15','2024-08-16'],
        'value': [68,70]
    }
)
for i in range(3):
    # Appends are no problem
    df.write_parquet('./example2', **kwargs)

df = pl.DataFrame(
    {
        'type': ['c','d'],
        'date': ['2024-08-15','2024-08-16'],
        'value': [68,70]
    }
)
for i in range(3):
    # Appends are no problem
    df.write_parquet('./example2', **kwargs)


df = pl.scan_parquet('./example2/').collect()
print(df)
```

The first 3 writes are duplicates of (a, b), and the second batch of 3 writes are duplicates of (c, d). It all gets written, and the `scan_parquet` will read the dataset successfully.

```
$ python main2.py 
shape: (12, 3)
┌────────────┬───────┬──────┐
│ date       ┆ value ┆ type │
│ ---        ┆ ---   ┆ ---  │
│ str        ┆ i64   ┆ str  │
╞════════════╪═══════╪══════╡
│ 2024-08-15 ┆ 68    ┆ a    │
│ 2024-08-15 ┆ 68    ┆ a    │
│ 2024-08-15 ┆ 68    ┆ a    │
│ 2024-08-16 ┆ 70    ┆ b    │
│ 2024-08-16 ┆ 70    ┆ b    │
│ …          ┆ …     ┆ …    │
│ 2024-08-15 ┆ 68    ┆ c    │
│ 2024-08-15 ┆ 68    ┆ c    │
│ 2024-08-16 ┆ 70    ┆ d    │
│ 2024-08-16 ┆ 70    ┆ d    │
│ 2024-08-16 ┆ 70    ┆ d    │
└────────────┴───────┴──────┘
(venv) ~/tmp/polars18242  [venv://h/c/t/p/v:3.12.3] 
$ tree example2/
example2/
├── type=a
│   ├── 106c2547792f4cc09261cb2ade8a184b-0.parquet
│   ├── 5a57a91e8cdd47cc8c8265763d73af09-0.parquet
│   └── 8e2ac5649d6b426a98223948aa641955-0.parquet
├── type=b
│   ├── 106c2547792f4cc09261cb2ade8a184b-0.parquet
│   ├── 5a57a91e8cdd47cc8c8265763d73af09-0.parquet
│   └── 8e2ac5649d6b426a98223948aa641955-0.parquet
├── type=c
│   ├── 8334576790a54d309a90d3ba30e12a79-0.parquet
│   ├── b1bf499677c240d391fe5d816f8dd8ae-0.parquet
│   └── faa85c76e629495b83c042e09e1a7961-0.parquet
└── type=d
    ├── 8334576790a54d309a90d3ba30e12a79-0.parquet
    ├── b1bf499677c240d391fe5d816f8dd8ae-0.parquet
    └── faa85c76e629495b83c042e09e1a7961-0.parquet

5 directories, 12 files
```
