### ISSUE TITLE
vstack allows stacking data frames with different numbers of columns (causing later a PanicException)

### ISSUE THREAD

**Issue by clo-vis** [pola-rs/polars#19644]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from polars import DataFrame
f = DataFrame().vstack(DataFrame({"a": [1]})) # no error
str(f) # Panic
```

### Log output

```shell
thread '<unnamed>' panicked at crates\polars-core\src\fmt.rs:567:13:
The column lengths in the DataFrame are not equal.
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".....\Lib\site-packages\polars\dataframe\frame.py", line 1178, in __str__
    return self._df.as_str()
           ^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: The column lengths in the DataFrame are not equal.
```

### Issue description

This is a regression.
The code used to work (until polars 1.9.0); print(f) used to show:

```
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
```

### Expected behavior

No invalid data frame is created or an exception is raised at the site an invalid data frame would be created.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.12.0
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.12.0
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              18.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0
```

</details>

**Comment by cmdlineluser** [comment]
I think this was fixed on main a little earlier:

- https://github.com/pola-rs/polars/issues/19641

**Comment by ritchie46** [comment]
This one isn't fixed yet, but it should raise an error instead of panic.

**Comment by ritchie46** [comment]
Never mind. I was on an old commit. Fixed on main.
