### ISSUE TITLE
`join` fails because of an uninstructed cast from int to array[int, x] on 1.14.0

### ISSUE THREAD

**Issue by TNieuwdorp** [pola-rs/polars#19763]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import numpy as np

dtype = [("id", "<i4")]
data = np.array([[(1,), (2,)]], dtype=dtype)

df = pl.LazyFrame(data).explode(pl.col("*"))

other_df = pl.LazyFrame({"node": [1]})

result = df.join(other_df, left_on="id", right_on="node").collect()

print(result)
```

### Issue description

When joining two LazyFrames, one constructed from a numpy structured array, and then exploded, the schema reflects the change, but during a join operation this still goes wrong.

The state of the two LazyFrames before the join:
![image](https://github.com/user-attachments/assets/442cfc7d-050a-4815-bb35-351f65077bcf)

The error of the join:
![image](https://github.com/user-attachments/assets/db475d60-8e73-4814-84ee-7f57f4012ffb)

This error also occurs when optimizations are turned off:
![image](https://github.com/user-attachments/assets/37d2530a-dc89-44fa-8ded-482cb04f540b)

Explicitly casting the columns to int32 before the operation seems to work:
![image](https://github.com/user-attachments/assets/51d83646-db22-4cac-8d72-fbe1c745890a)

### Expected behavior

I expect the data type to not be an array, and the join to succeed.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              1.14.0
Index type:          UInt32
Platform:            macOS-15.0.1-x86_64-i386-64bit
Python:              3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2023.12.2
gevent               <not installed>
great_tables         0.10.0
matplotlib           3.8.4
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             3.1.2
pandas               2.2.2
pyarrow              14.0.2
pydantic             1.10.15
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             0.8.2
xlsxwriter           <not installed>
</details>

**Comment by alexander-beedie** [comment]
This should have been fixed by https://github.com/pola-rs/polars/pull/19753, and we have already made a new patch release available - please update to `1.13.1` 👍

**Comment by TNieuwdorp** [comment]
@alexander-beedie Unfortunately that patch doesn't fix the problem, and it still occurs exactly as described.

**Comment by alexander-beedie** [comment]
Hmm, surprising! Are you able to create a small reproducible test-case that you can paste in to the Issue report?

**Comment by nameexhaustion** [comment]
Did you by any chance happen to have exploded the `pgm_id` column at some point?

**Comment by TNieuwdorp** [comment]
Yes, `explode()` is applied to the data!
![image](https://github.com/user-attachments/assets/741e568f-83cd-4d6e-ba67-fb22d3ad9680)

The original data comes from a structured numpy array (although since you reproduced it without that, it might not be relevant)
![image](https://github.com/user-attachments/assets/83ccacb7-aa53-43b2-8a05-cbd144fe96df)

**Comment by TNieuwdorp** [comment]
@nameexhaustion Unfortunately the error persists on 1.14.0 and it seems to be caused by something else...

**Comment by TNieuwdorp** [comment]
@ritchie46 @nameexhaustion I've updated the original issue with an MRE
