### ISSUE TITLE
`scan_parquet` raises PanicError when using `collect` after `filter`

### ISSUE THREAD

**Issue by Duy-X** [pola-rs/polars#20510]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl


data = {
    "name": ["a", "b"],
    "data": [
        {"title": "Title", "data": [0, 1, 3]},
        {"title": "Title", "data": [0, 1, 3]},
    ],
}

pl.DataFrame(data).write_parquet("data.parquet")

ldf = pl.scan_parquet("data.parquet")

print(ldf.collect())
# shape: (2, 2)
# ┌──────┬─────────────────────┐
# │ name ┆ data                │
# │ ---  ┆ ---                 │
# │ str  ┆ struct[2]           │
# ╞══════╪═════════════════════╡
# │ a    ┆ {"Title",[0, 1, 3]} │
# │ b    ┆ {"Title",[0, 1, 3]} │
# └──────┴─────────────────────┘

print(ldf.collect().filter(pl.col("name") == "b"))
# shape: (1, 2)
# ┌──────┬─────────────────────┐
# │ name ┆ data                │
# │ ---  ┆ ---                 │
# │ str  ┆ struct[2]           │
# ╞══════╪═════════════════════╡
# │ b    ┆ {"Title",[0, 1, 3]} │
# └──────┴─────────────────────┘

print(ldf.collect().lazy().filter(pl.col("name") == "b").collect())
# shape: (1, 2)
# ┌──────┬─────────────────────┐
# │ name ┆ data                │
# │ ---  ┆ ---                 │
# │ str  ┆ struct[2]           │
# ╞══════╪═════════════════════╡
# │ b    ┆ {"Title",[0, 1, 3]} │
# └──────┴─────────────────────┘

with pl.Config(verbose=True):
    print(ldf.filter(pl.col("name") == "b").collect())


```

### Log output

```shell
parquet scan with parallel = Columns
thread 'polars-0' panicked at crates/polars-arrow/src/array/struct_/mod.rs:120:56:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("The children DataTypes of a StructArray must equal the children data types.\n                         However, the field 1 has data type LargeList(Field { name: \"item\", dtype: UInt64, is_nullable: true, metadata: None }) but the value has data type UInt64"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/xomnia/repos/alliander/delta-lake-test/example.py", line 38, in <module>
    print(ldf.filter(pl.col("name") == "b").collect())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xomnia/repos/alliander/delta-lake-test/.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2043, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("The children DataTypes of a StructArray must equal the children data types.\n                         However, the field 1 has data type LargeList(Field { name: \"item\", dtype: UInt64, is_nullable: true, metadata: None }) but the value has data type UInt64"))
```

### Issue description

If I scan a simple parquet file with a Struct column, I get a `PanicException` when I filter the LazyFrame and collect. I don't get the error if I collect first and then filter, nor do I get the error when I turn the full DataFrame into a LazyFrame first, and then filter and collect again.

(Not sure whether this is a bug or just not supported)

### Expected behavior

To be able to do:

```python
print(ldf.filter(pl.col("name") == "b").collect())
# shape: (1, 2)
# ┌──────┬─────────────────────┐
# │ name ┆ data                │
# │ ---  ┆ ---                 │
# │ str  ┆ struct[2]           │
# ╞══════╪═════════════════════╡
# │ b    ┆ {"Title",[0, 1, 3]} │
# └──────┴─────────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.18.0
Index type:          UInt32
Platform:            macOS-14.7-arm64-arm-64bit
Python:              3.12.6 (main, Sep  9 2024, 21:36:32) [Clang 18.1.8 ]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                1.35.90
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.22.3
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.10.0
nest_asyncio         <not installed>
numpy                2.2.1
openpyxl             <not installed>
pandas               <not installed>
pyarrow              18.1.0
pydantic             2.10.4
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
Yeah - looks to be a bug.

It runs with the predicate_pushdown optimization disabled.

```python
ldf.filter(pl.col("name") == "b").collect(predicate_pushdown=False)
# shape: (1, 2)
# ┌──────┬─────────────────────┐
# │ name ┆ data                │
# │ ---  ┆ ---                 │
# │ str  ┆ struct[2]           │
# ╞══════╪═════════════════════╡
# │ b    ┆ {"Title",[0, 1, 3]} │
# └──────┴─────────────────────┘
```

**Comment by astrowonk** [comment]
Just ran into this same issue.  Using `polars==1.17.0` until the fix is released, which doesn't crash for me.

**Comment by choucavalier** [comment]
This is still happening with the bleeding edge 1.20.0

Passing `predicate_pushdown=False` suppresses the error

**Comment by astrowonk** [comment]
> This is still happening with the bleeding edge 1.20.0
> 
> Passing `predicate_pushdown=False` suppresses the error

I installed polars 1.2 from pypi and, at least for local parquet files, I can collect after a filter on a lazyframe from scan_parquet.

I haven't tested it yet on my usual work use case which is parquet files on Azure blob storage, but will post if that still crashes.

**Comment by ritchie46** [comment]
@coastalwhite can you take a look?

**Comment by astrowonk** [comment]
@ritchie46 I tested 1.20.0 with `scan_parquet` with Azure blobs and 1.20.0 isn't crashing - but is _much_ slower than 1.17.0 doing aggregations on lazy frames. Things that took 3 seconds in 1.17 are taking 14 seconds in 1.20.0.

**Comment by coastalwhite** [comment]
We would really need a reproduction example. The original issue does not produce an issue anymore.

**Comment by choucavalier** [comment]
@coastalwhite can i privately share some data and code with you to reproduce the error?

**Comment by coastalwhite** [comment]
> [@coastalwhite](https://github.com/coastalwhite) can i privately share some data and code with you to reproduce the error?

Yes, of course. The easiest is to send me a Discord private message. You can find me in the Polars Discord under the same username. <https://discord.gg/4UfP5cfBE7>
