### ISSUE TITLE
Can't read delta tables from ADLS without use_pyarrow=True

### ISSUE THREAD

**Issue by jakubkovac** [pola-rs/polars#20545]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
tenant_id = "TENANT_ID"
container = "CONTAINER"
account = "ACCOUNT_URL"
file_path = "MY_PATH/poc_polars_test"
adls_path = f"abfss://{container}@{account}/{file_path}"
storage_options = {"tenant_id": tenant_id, "use_azure_cli": "true"}

import deltalake
import polars as pl
# 1. This works:
df = deltalake.DeltaTable(adls_path, storage_options=storage_options)

# 2. This also works:
df2 = pl.from_arrow(df.to_pyarrow_table())

# 3. This also works and takes ~7s
df3 = pl.read_delta(adls_path, storage_options=storage_options, use_pyarrow=True)

# 4. This does not work on polars > 0.13.1, unless running through ipykernel(tested through vscode), tested polars versions: 1.13.1, 1.14.0 and latest 1.18.0
# in jupyter context it takes ~20s
df4 = pl.read_delta(adls_path, storage_options=storage_options)
```
[poc_polars_test.zip](https://github.com/user-attachments/files/18300511/poc_polars_test.zip)

### Log output

```shell
Traceback (most recent call last):
  File "c:\Users\JAKUB.KOVAC\Documents\Moje\polars_issue\read_delta.py", line 33, in <module>
    df4 = pl.read_delta(adls_path, storage_options=storage_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\JAKUB.KOVAC\Documents\Moje\polars_issue\.venv\Lib\site-packages\polars\io\delta.py", line 149, in read_delta
    return df.collect()
           ^^^^^^^^^^^^
  File "c:\Users\JAKUB.KOVAC\Documents\Moje\polars_issue\.venv\Lib\site-packages\polars\lazyframe\frame.py", line 2043, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: Generic MicrosoftAzure error: Error after 2 retries in 2.4330126s, max_retries:2, retry_timeout:10s, source:error sending request for url (https://REDACTED_URL/poc_polars_test/part-00000-1f53436b-681b-4d81-97ce-70c625ff7ba1-c000.snappy.parquet)
```

### Issue description

The default of `read_delta()` `use_pyarrow=False` should work as well. I'm including the delta table as well but my guess is that it is irrelevant, since reading the data locally works as expected.

### Expected behavior

I would expect the read_delta function to work regardless of the `use_pyarrow` argument value and regardless of whether it runs in a jupyter kernel or not.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.18.0
Index type:          UInt32
Platform:            Windows-11-10.0.22631-SP0
Python:              3.12.5 (main, Aug 14 2024, 04:23:18) [MSC v.1929 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
Azure CLI            2.59.0
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       1.19.0
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.23.1
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by Bidek56** [comment]
`df = pl.scan_delta(source=delta_path, storage_options=storage_options, use_pyarrow=False)`
`df = pl.read_delta(source=delta_path, storage_options=storage_options, use_pyarrow=False)`
and 
`df = pl.scan_delta(source=delta_path, storage_options=storage_options, use_pyarrow=True)`
`df = pl.read_delta(source=delta_path, storage_options=storage_options, use_pyarrow=True)`
works fine using Polars `1.19.0`, `Python 3.12.8` on `MacOs ARM64 Darwin Kernel Version 23.6.0`
Execution time will depend on your network connection to Azure DC, so it's irrelevant here.

**Comment by jakubkovac** [comment]
The issue still persists for me with polars `1.19.0` and `python 3.12.8` on win 11 (unless using ipykernel).

**Comment by Bidek56** [comment]
Have you tried saving to a local disk?
It says `Generic MicrosoftAzure error`, hence it could be an Azure lib issue.
Does it work with Minio/s3 like storage?

**Comment by jakubkovac** [comment]
Saving the delta table to local and reading from local works.
Cannot test with Minio/s3, only have access to Azure on this machine.

I've also tested [#20583](https://github.com/pola-rs/polars/pull/20583) compiling polars from main after this was merged, but with no success.
Also tested this with the latest version of Azure CLI `2.67.0`

**Comment by nameexhaustion** [comment]
Could you try again on the latest main? We fixed a bug where the credentials got overridden in some cases (https://github.com/pola-rs/polars/pull/20652)

**Comment by jakubkovac** [comment]
That also did not fix my issue, also tried installing `azure-identity` just in case, but didn't help.
```
[CloudOptions::build_azure]: Using credential provider Python(PythonCredentialProvider(PythonFunction(Py(0x1e8115652b0))))
POLARS PREFETCH_SIZE: 24
querying metadata of 1/1 files...
object store cache key: REDACTED.snappy.parquet S { url_base: "abfss://REDACTED", cloud_options: Some(C { max_retries: 2, file_cache_ttl: 3600, config: Some(Azure([(AuthorityId, REDACTED), (UseAzureCli, "true")])), credential_provider: REDACTED }) }
[FetchedCredentialsCache]: Call update_func: current_time = 1736949361, last_fetched_expiry = 0
[CredentialProviderAzure]: self.account_name = 'REDACTED' POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY = None
[FetchedCredentialsCache]: Finish update_func: new expiry = 1736953490 (in 4128 seconds)
[FetchedCredentialsCache]: Using cached credentials: current_time = 1736949364, expiry = 1736953490 (in 4126 seconds)
[PolarsObjectStore]: got error: Generic MicrosoftAzure error: Error after 2 retries in 1.5576816s, max_retries:2, retry_timeout:10s, source:error sending request for url REDACTED.parquet), will attempt re-build
[CloudOptions::build_azure]: Using credential provider Python(PythonCredentialProvider(PythonFunction(Py(0x1e8115652b0))))
[FetchedCredentialsCache]: Call update_func: current_time = 1736949365, last_fetched_expiry = 0
[CredentialProviderAzure]: self.account_name = 'REDACTED' POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY = None
[FetchedCredentialsCache]: Finish update_func: new expiry = 1736953490 (in 4124 seconds)
[FetchedCredentialsCache]: Using cached credentials: current_time = 1736949368, expiry = 1736953490 (in 4122 seconds)
```

**Comment by jakubkovac** [comment]
Not sure when this got fixed exactly but I can confirm that with: 
polars 1.31.0
deltalake 1.1.0
Azure cli 2.59.0
Everything works as expected.
Thank you 😊
