### ISSUE TITLE
PanicException InvalidHeaderValue when reading a table from s3

### ISSUE THREAD

**Issue by aldder** [pola-rs/polars#20650]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import deltalake
import polars as pl
import os
os.environ['RUST_BACKTRACE'] = 'full'

print(pl.__version__)
print(deltalake.__version__)

bucket = 'XXXX'

pl.DataFrame(
    {
        'a': ['1', '2', '3'],
        'b': [4, 5, 6],
        'c': [7.0, 8.0, 9.0]
    },
    schema={
        'a': pl.String,
        'b': pl.Int64,
        'c': pl.Float64
    }
).write_delta(
    f's3://{bucket}/delta_table/',
    storage_options={
        'region': 'eu-west-1'
    }
)

print('create done')

pl.read_delta(
    f's3://{bucket}/delta_table/',
    storage_options={
        'region': 'eu-west-1'
    }
)

print('read done')
```

### Log output

```shell
1.19.0
0.23.2
create done
thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\object_store-0.11.2\src\aws\credential.rs:229:71:
called `Result::unwrap()` on an `Err` value: InvalidHeaderValue
stack backtrace:
   0:     0x7ff9ea84554c - ffi_select_with_compiled_path
   1:     0x7ff9e595c5da - PyInit_polars
   2:     0x7ff9ea844ff7 - ffi_select_with_compiled_path
   3:     0x7ff9ea8453a4 - ffi_select_with_compiled_path
   4:     0x7ff9ea844ca4 - ffi_select_with_compiled_path
   5:     0x7ff9ea8674f9 - ffi_select_with_compiled_path
   6:     0x7ff9ea86744f - ffi_select_with_compiled_path
   7:     0x7ff9ea867cbe - ffi_select_with_compiled_path
   8:     0x7ff9ea9a8b21 - ffi_select_with_compiled_path
   9:     0x7ff9ea9a8f10 - ffi_select_with_compiled_path
  10:     0x7ff9e5a4f207 - ffi_select_with_compiled_path
  11:     0x7ff9e5a3780e - ffi_select_with_compiled_path
  12:     0x7ff9e5b22041 - ffi_select_with_compiled_path
  13:     0x7ff9e5b1ecd7 - ffi_select_with_compiled_path
  14:     0x7ff9e5b44655 - ffi_select_with_compiled_path
  15:     0x7ff9e72e5c86 - ffi_select_with_compiled_path
  16:     0x7ff9e5bb7324 - ffi_select_with_compiled_path
  17:     0x7ff9e7610bcf - ffi_select_with_compiled_path
  18:     0x7ff9e760d5e2 - ffi_select_with_compiled_path
  19:     0x7ff9e7670df4 - ffi_select_with_compiled_path
  20:     0x7ff9e767025f - ffi_select_with_compiled_path
  21:     0x7ff9e76626eb - ffi_select_with_compiled_path
  22:     0x7ff9e765bb94 - ffi_select_with_compiled_path
  23:     0x7ff9e76567f7 - ffi_select_with_compiled_path
  24:     0x7ff9e77eb595 - ffi_select_with_compiled_path
  25:     0x7ff9e758953b - ffi_select_with_compiled_path
  26:     0x7ff9e94c9b15 - ffi_select_with_compiled_path
  27:     0x7ff9e900217f - ffi_select_with_compiled_path
  28:     0x7ff9e94972a2 - ffi_select_with_compiled_path
  29:     0x7ffa21d86b83 - PyUnicode_InsertThousandsGrouping
  30:     0x7ffa21db4d4f - PyObject_Vectorcall
  31:     0x7ffa21db4cb5 - PyObject_Vectorcall
  32:     0x7ffa21db61ad - PyEval_EvalFrameDefault
  33:     0x7ffa21df4d18 - PyEval_EvalCode
  34:     0x7ffa21df4689 - PyEval_EvalCode
  35:     0x7ffa21d776a4 - PyObject_CallMethodObjArgs
  36:     0x7ffa21d77768 - PyObject_CallMethodObjArgs
  37:     0x7ffa21dd8320 - PyImport_FixupExtensionObject
  38:     0x7ffa21dd7f1a - PyRun_SimpleFileObject
  39:     0x7ffa21dd7579 - PyRun_AnyFileObject
  40:     0x7ffa21dd73be - PyFile_GetLine
  41:     0x7ffa21dd729b - PyFile_GetLine
  42:     0x7ffa21e2cfcb - Py_RunMain
  43:     0x7ffa21e2cd7d - Py_RunMain
  44:     0x7ffa21e19e2d - Py_Main
  45:     0x7ff60f351230 - <unknown>
  46:     0x7ffadbd3259d - BaseThreadInitThunk
  47:     0x7ffaddceaf38 - RtlUserThreadStart
Traceback (most recent call last):
  File "c:\Users\xxx\test.py", line 33, in <module>
    pl.read_delta(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\polars\io\delta.py", line 149, in read_delta
    return df.collect()
           ^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\polars\lazyframe\frame.py", line 2057, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidHeaderValue
```

### Issue description

Hello everyone, I don't know how come but since a few days this error started to appear, I tried to run the script even with combinations of old polars/delta-rs versions, but the error persists.

(The table can be corretly read with:)
```python
deltalake.DeltaTable(
        f's3://{bucket}/delta_table/',
        storage_options={'region': 'eu-west-1'}
    ).to_pandas()
```

### Expected behavior

correctly read the table

### Installed versions

<details>

```
--------Version info---------
Polars:              1.19.0
Index type:          UInt32
Platform:            Windows-11-10.0.22631-SP0
Python:              3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.5.0
azure.identity       <not installed>
boto3                1.35.94
cloudpickle          3.1.0
connectorx           <not installed>
deltalake            0.23.2
fastexcel            <not installed>
fsspec               2024.12.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.10.0
nest_asyncio         1.6.0
numpy                2.2.1
openpyxl             3.1.5
pandas               2.2.3
pyarrow              18.1.0
pydantic             2.10.4
pyiceberg            <not installed>
sqlalchemy           2.0.36
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
None
```

</details>

**Comment by nameexhaustion** [comment]
This should be fixed by https://github.com/pola-rs/polars/pull/20611

**Comment by aldder** [comment]
Hello @nameexhaustion 
unfortunatelly this issue still persists
polars 1.20.0
deltalake 0.24.0

**Comment by nameexhaustion** [comment]
I am unfortunately not able to take any action on this, as I cannot reproduce the issue - can you confirm -

* Was there an older version of polars that doesn't have this issue?
* Are you able to scan from other S3 buckets?
* Are there any special characters (i.e. non alphabet or numeric) in either the AWS access key ID / secret key, or the bucket name?

If there's any additional non-sensitive information that you feel could be related, please also include that

**Comment by aldder** [comment]
Hi @nameexhaustion 
_"Was there an older version of polars that doesn't have this issue?"_ 
With the version 1.12.0 the error doesn't occur.

_"Are you able to scan from other S3 buckets?"_ 
Nope.

_"Are you able to read files from the bucket using a different function - e.g. scan_csv?"_ 
If i try to run 
```python 
pl.scan_csv('s3://XXXX/test_csv.csv').collect()
``` 
it returns the warning:
```
UserWarning: '(default_)region' not set; polars will try to get it from bucket

Set the region manually to silence this warning.
  df = pl.scan_csv('s3://XXXX/test_csv.csv').collect()
```
but it works and read the file,

If I put the region:
```python
df = pl.scan_csv('s3://XXXX/test_csv.csv',
                 storage_options={'aws_region': 'eu-west-1'}).collect()
```
i get the error.

_"Are there any special characters (i.e. non alphabet or numeric) in either the AWS access key ID / secret key, or the bucket name?"_
I don't see anything particularly strange.

---

An interesting case i noticed is that if I run the following code:
```python
dt = deltalake.DeltaTable(
    f's3://{bucket}/test_delta_table/',
    storage_options={
        'region': 'eu-west-1'
    })

pl.scan_delta(dt).collect()
```
everything works and no error.

But if run this:
```python
dt = deltalake.DeltaTable(
    f's3://{bucket}/test_delta_table/',
    storage_options={
        'region': 'eu-west-1'
    })

pl.scan_delta(
    dt,
    storage_options={
        'aws_region': 'eu-west-1'
    }
).collect()
```
it returns the warning:
```
RuntimeWarning: When supplying a DeltaTable directly, `version`, `storage_options`, and `delta_table_options` are ignored.
```
but then i get the error.

**Comment by abhishek-rajvir** [comment]
So , if anyone is still having issue use this
                storage_options={
                    "aws_access_key_id": creds.access_key,
                    "aws_secret_access_key": creds.secret_key,
                    "region": hook.conn_region_name 
                  # or "region" : "ap-south-1"
                }
