### ISSUE TITLE
Out-of-memory in PartitionByKey

### ISSUE THREAD

**Issue by djouallah** [pola-rs/polars#21778]
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
z.with_columns(pl.col(columns).cast(pl.Float64),year=pl.col("SETTLEMENTDATE").dt.iso_year()).sink_parquet(
    PartitionByKey(
        f"/lakehouse/default/Tables/T{total_files}/polars/{{key[0].value}}/0000.parquet",
        by=[pl.col.year],
        include_key=False,
    ),
    mkdir=True
    )

```

### Log output

```shell

```

### Issue description

out of memory

### Expected behavior

maybe I am doing something wrong, but i was expecting the sink to create new parquet files when there is enough data to be written, but it seems,  polars it is trying to read the whole data then generate 1 parquet file by partition 

### Installed versions

1.25.2

**Comment by coastalwhite** [comment]
The partition by scales linearly in memory consumption until you reach 128 partitions afterwards it will start buffering everything. There is no real alternative unless we start spilling to disk.

**Comment by ion-elgreco** [comment]
Not exactly sure how the partitioned writes work in Polars but in deltalake if you presort the data based on partition then you are buffering less since you are opening less partitioned writers in parallel

**Comment by coastalwhite** [comment]
> Not exactly sure how the partitioned writes work in Polars but in deltalake if you presort the data based on partition then you are buffering less since you are opening less partitioned writers in parallel and waiting for the buffer to fill up before putting the objects 

Yeah, 100% true. We don't have that strategy now but we will have a `PartitionParted` that can do this efficiently for parted (e.g. sorted or group_by) data. We don't have it yet. The problem with sorting is that it (usually) requires having seen all elements so you will OOM in the sort. `PartitionByKey` is really ment for when you know the amount of partitions you are going to be writing is small.

**Comment by ritchie46** [comment]
That's a strategy we can look into, once we implemented OOC sort: https://github.com/pola-rs/polars/issues/20947

Currently the focus is first, optimizing and implementing the core streaming operators, then we will do OOC.

**Comment by djouallah** [comment]
is there an example how to use maxpersize, could not find any example,

**Comment by djouallah** [comment]
sorry, I am confused now, I changed to PartitionMaxSize , but still getting OOM

 ```
 z.with_columns(pl.col(columns).cast(pl.Float64),year=pl.col("SETTLEMENTDATE").dt.iso_year()).sink_parquet(
                                PartitionMaxSize(f"/lakehouse/default/Tables/T{total_files}/{{part}}.parquet", max_size=5_000_000)
                                )
```
there is no sort in my transformation, I am just reading a lot of csv files, Polars don't need to see the whole data, I thought, the moment it process enough data, it will start generating new Parquet files ?

**Comment by ritchie46** [comment]
That's strange. What's your full query?

**Comment by djouallah** [comment]
```
!pip install polars --upgrade
  import polars as pl
  from polars.io.partition import PartitionMaxSize
  schema ={'I': pl.String,'UNIT': pl.String,'XX': pl.String,'VERSION': pl.String,'SETTLEMENTDATE': pl.String,'RUNNO': pl.String,
    'DUID': pl.String,'INTERVENTION': pl.String,'DISPATCHMODE': pl.String,'AGCSTATUS': pl.String,'INITIALMW': pl.String,
    'TOTALCLEARED': pl.String,'RAMPDOWNRATE': pl.String,'RAMPUPRATE': pl.String,'LOWER5MIN': pl.String,
    'LOWER60SEC': pl.String,'LOWER6SEC': pl.String,'RAISE5MIN': pl.String,'RAISE60SEC': pl.String,
    'RAISE6SEC': pl.String,'MARGINAL5MINVALUE': pl.String,'MARGINAL60SECVALUE': pl.String,
    'MARGINAL6SECVALUE': pl.String,'MARGINALVALUE': pl.String,'VIOLATION5MINDEGREE': pl.String,
    'VIOLATION60SECDEGREE': pl.String,'VIOLATION6SECDEGREE': pl.String,'VIOLATIONDEGREE': pl.String,
    'LOWERREG': pl.String,'RAISEREG': pl.String,'AVAILABILITY': pl.String,'RAISE6SECFLAGS': pl.String,
    'RAISE60SECFLAGS': pl.String,'RAISE5MINFLAGS': pl.String,'RAISEREGFLAGS': pl.String,
    'LOWER6SECFLAGS': pl.String,'LOWER60SECFLAGS': pl.String,'LOWER5MINFLAGS': pl.String,
    'LOWERREGFLAGS': pl.String,'RAISEREGAVAILABILITY': pl.String,'RAISEREGENABLEMENTMAX': pl.String,
    'RAISEREGENABLEMENTMIN': pl.String,'LOWERREGAVAILABILITY': pl.String,'LOWERREGENABLEMENTMAX': pl.String,
    'LOWERREGENABLEMENTMIN': pl.String,'RAISE6SECACTUALAVAILABILITY': pl.String,
    'RAISE60SECACTUALAVAILABILITY': pl.String,'RAISE5MINACTUALAVAILABILITY': pl.String,
    'RAISEREGACTUALAVAILABILITY': pl.String,'LOWER6SECACTUALAVAILABILITY': pl.String,
    'LOWER60SECACTUALAVAILABILITY': pl.String,'LOWER5MINACTUALAVAILABILITY': pl.String,'LOWERREGACTUALAVAILABILITY': pl.String}
  raw = pl.scan_csv(x, skip_rows=1, schema=schema, has_header=False,truncate_ragged_lines=True, include_file_paths="filename")
  transform =(
      raw
      .filter( (pl.col("I")=='D') &  (pl.col("UNIT")=='DUNIT') & (pl.col("VERSION")=='3') )
      .drop("XX","I")
  )
 
  z = transform.with_columns(pl.col("SETTLEMENTDATE").str.to_datetime())
  columns = list(set(transform.collect_schema().names()) - {'SETTLEMENTDATE','DUID','UNIT','filename'})
  z.with_columns(pl.col(columns).cast(pl.Float64),year=pl.col("SETTLEMENTDATE").dt.iso_year()).sink_parquet(
                                PartitionMaxSize(f"/lakehouse/default/Tables/T{total_files}/{{part}}.parquet", max_size=5_000_000)
                                )
```

**Comment by coastalwhite** [comment]
That really sounds unrelated to the partitioning sinks.

Does it work if you just call `.sink_parquet('/path/to/file.parquet')` with one file? And can you maybe share the output `plan.dot` file of `POLARS_VISUALIZE_PHYSICAL_PLAN=./plan.dot`?

**Comment by djouallah** [comment]
it does works, with 120 csv files for example but OOM with 1000 csv , i will share the plan.dot later

**Comment by djouallah** [comment]
digraph polars {
rankdir="BT"
4294967306 [label="parquet-partition-sink"];
4294967305 [label="with-columns\ncol(\"SETTLEMENTDATE\").dt.iso_year().alias(\"year\")"];
4294967304 [label="select\ncol(\"UNIT\").alias(\"UNIT\")\ncol(\"VERSION\").strict_cast(Float64).alias(\"VERSION\")\ncol(\"_POLARS_TMP_0\").alias(\"SETTLEMENTDATE\")\ncol(\"RUNNO\").strict_cast(Float64).alias(\"RUNNO\")\ncol(\"DUID\").alias(\"DUID\")\ncol(\"INTERVENTION\").strict_cast(Float64).alias(\"INTERVENTION\")\ncol(\"DISPATCHMODE\").strict_cast(Float64).alias(\"DISPATCHMODE\")\ncol(\"AGCSTATUS\").strict_cast(Float64).alias(\"AGCSTATUS\")\ncol(\"INITIALMW\").strict_cast(Float64).alias(\"INITIALMW\")\ncol(\"TOTALCLEARED\").strict_cast(Float64).alias(\"TOTALCLEARED\")\ncol(\"RAMPDOWNRATE\").strict_cast(Float64).alias(\"RAMPDOWNRATE\")\ncol(\"RAMPUPRATE\").strict_cast(Float64).alias(\"RAMPUPRATE\")\ncol(\"LOWER5MIN\").strict_cast(Float64).alias(\"LOWER5MIN\")\ncol(\"LOWER60SEC\").strict_cast(Float64).alias(\"LOWER60SEC\")\ncol(\"LOWER6SEC\").strict_cast(Float64).alias(\"LOWER6SEC\")\ncol(\"RAISE5MIN\").strict_cast(Float64).alias(\"RAISE5MIN\")\ncol(\"RAISE60SEC\").strict_cast(Float64).alias(\"RAISE60SEC\")\ncol(\"RAISE6SEC\").strict_cast(Float64).alias(\"RAISE6SEC\")\ncol(\"MARGINAL5MINVALUE\").strict_cast(Float64).alias(\"MARGINAL5MINVALUE\")\ncol(\"MARGINAL60SECVALUE\").strict_cast(Float64).alias(\"MARGINAL60SECVALUE\")\ncol(\"MARGINAL6SECVALUE\").strict_cast(Float64).alias(\"MARGINAL6SECVALUE\")\ncol(\"MARGINALVALUE\").strict_cast(Float64).alias(\"MARGINALVALUE\")\ncol(\"VIOLATION5MINDEGREE\").strict_cast(Float64).alias(\"VIOLATION5MINDEGREE\")\ncol(\"VIOLATION60SECDEGREE\").strict_cast(Float64).alias(\"VIOLATION60SECDEGREE\")\ncol(\"VIOLATION6SECDEGREE\").strict_cast(Float64).alias(\"VIOLATION6SECDEGREE\")\ncol(\"VIOLATIONDEGREE\").strict_cast(Float64).alias(\"VIOLATIONDEGREE\")\ncol(\"LOWERREG\").strict_cast(Float64).alias(\"LOWERREG\")\ncol(\"RAISEREG\").strict_cast(Float64).alias(\"RAISEREG\")\ncol(\"AVAILABILITY\").strict_cast(Float64).alias(\"AVAILABILITY\")\ncol(\"RAISE6SECFLAGS\").strict_cast(Float64).alias(\"RAISE6SECFLAGS\")\ncol(\"RAISE60SECFLAGS\").strict_cast(Float64).alias(\"RAISE60SECFLAGS\")\ncol(\"RAISE5MINFLAGS\").strict_cast(Float64).alias(\"RAISE5MINFLAGS\")\ncol(\"RAISEREGFLAGS\").strict_cast(Float64).alias(\"RAISEREGFLAGS\")\ncol(\"LOWER6SECFLAGS\").strict_cast(Float64).alias(\"LOWER6SECFLAGS\")\ncol(\"LOWER60SECFLAGS\").strict_cast(Float64).alias(\"LOWER60SECFLAGS\")\ncol(\"LOWER5MINFLAGS\").strict_cast(Float64).alias(\"LOWER5MINFLAGS\")\ncol(\"LOWERREGFLAGS\").strict_cast(Float64).alias(\"LOWERREGFLAGS\")\ncol(\"RAISEREGAVAILABILITY\").strict_cast(Float64).alias(\"RAISEREGAVAILABILITY\")\ncol(\"RAISEREGENABLEMENTMAX\").strict_cast(Float64).alias(\"RAISEREGENABLEMENTMAX\")\ncol(\"RAISEREGENABLEMENTMIN\").strict_cast(Float64).alias(\"RAISEREGENABLEMENTMIN\")\ncol(\"LOWERREGAVAILABILITY\").strict_cast(Float64).alias(\"LOWERREGAVAILABILITY\")\ncol(\"LOWERREGENABLEMENTMAX\").strict_cast(Float64).alias(\"LOWERREGENABLEMENTMAX\")\ncol(\"LOWERREGENABLEMENTMIN\").strict_cast(Float64).alias(\"LOWERREGENABLEMENTMIN\")\ncol(\"RAISE6SECACTUALAVAILABILITY\").strict_cast(Float64).alias(\"RAISE6SECACTUALAVAILABILITY\")\ncol(\"RAISE60SECACTUALAVAILABILITY\").strict_cast(Float64).alias(\"RAISE60SECACTUALAVAILABILITY\")\ncol(\"RAISE5MINACTUALAVAILABILITY\").strict_cast(Float64).alias(\"RAISE5MINACTUALAVAILABILITY\")\ncol(\"RAISEREGACTUALAVAILABILITY\").strict_cast(Float64).alias(\"RAISEREGACTUALAVAILABILITY\")\ncol(\"LOWER6SECACTUALAVAILABILITY\").strict_cast(Float64).alias(\"LOWER6SECACTUALAVAILABILITY\")\ncol(\"LOWER60SECACTUALAVAILABILITY\").strict_cast(Float64).alias(\"LOWER60SECACTUALAVAILABILITY\")\ncol(\"LOWER5MINACTUALAVAILABILITY\").strict_cast(Float64).alias(\"LOWER5MINACTUALAVAILABILITY\")\ncol(\"LOWERREGACTUALAVAILABILITY\").strict_cast(Float64).alias(\"LOWERREGACTUALAVAILABILITY\")\ncol(\"filename\").alias(\"filename\")"];
4294967303 [label="zip"];
4294967302 [label="in-memory-map"];
4294967301 [label="select\ncols: SETTLEMENTDATE"];
4294967307 [label="multiplexer"];
4294967300 [label="select\ncols: UNIT, VERSION, SETTLEMENTDATE, RUNNO, DUID, INTERVENTION, DISPATCHMODE, AGCSTATUS, INITIALMW, TOTALCLEARED, RAMPDOWNRATE, RAMPUPRATE, LOWER5MIN, LOWER60SEC, LOWER6SEC, RAISE5MIN, RAISE60SEC, RAISE6SEC, MARGINAL5MINVALUE, MARGINAL60SECVALUE, MARGINAL6SECVALUE, MARGINALVALUE, VIOLATION5MINDEGREE, VIOLATION60SECDEGREE, VIOLATION6SECDEGREE, VIOLATIONDEGREE, LOWERREG, RAISEREG, AVAILABILITY, RAISE6SECFLAGS, RAISE60SECFLAGS, RAISE5MINFLAGS, RAISEREGFLAGS, LOWER6SECFLAGS, LOWER60SECFLAGS, LOWER5MINFLAGS, LOWERREGFLAGS, RAISEREGAVAILABILITY, RAISEREGENABLEMENTMAX, RAISEREGENABLEMENTMIN, LOWERREGAVAILABILITY, LOWERREGENABLEMENTMAX, LOWERREGENABLEMENTMIN, RAISE6SECACTUALAVAILABILITY, RAISE60SECACTUALAVAILABILITY, RAISE5MINACTUALAVAILABILITY, RAISEREGACTUALAVAILABILITY, LOWER6SECACTUALAVAILABILITY, LOWER60SECACTUALAVAILABILITY, LOWER5MINACTUALAVAILABILITY, LOWERREGACTUALAVAILABILITY, filename"];
4294967299 [label="filter\n[([([(col(\"I\")) == (String(D))]) & ([(col(\"UNIT\")) == (String(DUNIT))])]) & ([(col(\"VERSION\")) == (String(3))])].alias(\"I\")"];
4294967298 [label="select\ncols: I, UNIT, VERSION, SETTLEMENTDATE, RUNNO, DUID, INTERVENTION, DISPATCHMODE, AGCSTATUS, INITIALMW, TOTALCLEARED, RAMPDOWNRATE, RAMPUPRATE, LOWER5MIN, LOWER60SEC, LOWER6SEC, RAISE5MIN, RAISE60SEC, RAISE6SEC, MARGINAL5MINVALUE, MARGINAL60SECVALUE, MARGINAL6SECVALUE, MARGINALVALUE, VIOLATION5MINDEGREE, VIOLATION60SECDEGREE, VIOLATION6SECDEGREE, VIOLATIONDEGREE, LOWERREG, RAISEREG, AVAILABILITY, RAISE6SECFLAGS, RAISE60SECFLAGS, RAISE5MINFLAGS, RAISEREGFLAGS, LOWER6SECFLAGS, LOWER60SECFLAGS, LOWER5MINFLAGS, LOWERREGFLAGS, RAISEREGAVAILABILITY, RAISEREGENABLEMENTMAX, RAISEREGENABLEMENTMIN, LOWERREGAVAILABILITY, LOWERREGENABLEMENTMAX, LOWERREGENABLEMENTMIN, RAISE6SECACTUALAVAILABILITY, RAISE60SECACTUALAVAILABILITY, RAISE5MINACTUALAVAILABILITY, RAISEREGACTUALAVAILABILITY, LOWER6SECACTUALAVAILABILITY, LOWER60SECACTUALAVAILABILITY, LOWER5MINACTUALAVAILABILITY, LOWERREGACTUALAVAILABILITY, filename"];
4294967297 [label="multi-scan-source"];
4294967297 -> 4294967298;
4294967298 -> 4294967299;
4294967299 -> 4294967300;
4294967300 -> 4294967307;
4294967307 -> 4294967301;
4294967301 -> 4294967302;
4294967302 -> 4294967303;
4294967307 -> 4294967303;
4294967303 -> 4294967304;
4294967304 -> 4294967305;
4294967305 -> 4294967306;
}

**Comment by coastalwhite** [comment]
There is a `in-memory map` there. It seems from the `dt.iso_year()`.

![Image](https://github.com/user-attachments/assets/60a04089-64af-405b-9e95-d857e7779638)

**Comment by coastalwhite** [comment]
If you provide a `format` to `to_datetime`, it is elementwise and will not produce the `in-memory map` and should be all good.

**Comment by ritchie46** [comment]
> There is a `in-memory map` there. It seems from the `str.to_datetime()`. This is because str.to_datetime is not elementwise.

Is that a bug on our end? Why does that need all the data?

**Comment by coastalwhite** [comment]
> > There is a `in-memory map` there. It seems from the `str.to_datetime()`. This is because str.to_datetime is not elementwise.
> 
> Is that a bug on our end? Why does that need all the data?

No, Orson discovered that recently. All the temporal conversions infer the format from the first few rows which makes them non-elementwise.

**Comment by ritchie46** [comment]
Right,we can't infer that differently per batch. That's a footgun. 😬

**Comment by ritchie46** [comment]
> As a workaround, if you provide a format to to_datetime, it is elementwise and will not produce the in-memory map and should be all good. 

Did that work @djouallah?

**Comment by djouallah** [comment]
@ritchie46 works perfectly !!!

**Comment by djouallah** [comment]
hopefully will be fixed by https://github.com/pola-rs/polars/pull/23980

**Comment by djouallah** [comment]
it is great job better than i hoped for

<img width="2052" height="952" alt="Image" src="https://github.com/user-attachments/assets/07bf0310-55e7-4a70-9633-d34c347d2ab0" />
