### ISSUE TITLE
Unable to read parquet files with list values in columns

### ISSUE THREAD

**Issue by ddutt** [pola-rs/polars#2448]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.12.14

#### What operating system are you using polars on?

Linux, Ubuntu 21.10

#### Describe your bug.

pl.read_parquet returns a RuntimeError when attempting to read parquet files that contain list as values in some of the columns

#### What are the steps to reproduce the behavior?

```python
import polars as pl
import numpy as np

pl.read_parquet('/tmp/pq-file-with-columns.parquet, use_pyarrow=False)
```

If we cannot reproduce the bug, it is unlikely that we will be able fix it.

#### What is the actual behavior?

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-029425c018d1> in <module>
----> 1 pl.read_parquet('/home/ddutt/work/suzieq/play/donna/new-parquet/routes/', use_pyarrow=False)

~/work/dsengines/.venv/lib/python3.7/site-packages/polars/io.py in read_parquet(source, columns, n_rows, use_pyarrow, memory_map, storage_options, parallel, **kwargs)
    782 
    783         return DataFrame._read_parquet(
--> 784             source_prep, columns=columns, n_rows=n_rows, parallel=parallel
    785         )
    786 

~/work/dsengines/.venv/lib/python3.7/site-packages/polars/internals/frame.py in _read_parquet(file, columns, n_rows, parallel)
    590         projection, columns = handle_projection_columns(columns)
    591         self = DataFrame.__new__(DataFrame)
--> 592         self._df = PyDataFrame.read_parquet(file, columns, projection, n_rows, parallel)
    593         return self
    594 

RuntimeError: Any(ArrowError(ExternalFormat("underlying IO error: Is a directory (os error 21)")))

In [18]: pl.read_parquet('/home/ddutt/work/suzieq/play/donna/new-parquet/routes/**/*.parquet', use_pyarrow=False)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-1b6d9bbdb96d> in <module>
----> 1 pl.read_parquet('/home/ddutt/work/suzieq/play/donna/new-parquet/routes/**/*.parquet', use_pyarrow=False)

~/work/dsengines/.venv/lib/python3.7/site-packages/polars/io.py in read_parquet(source, columns, n_rows, use_pyarrow, memory_map, storage_options, parallel, **kwargs)
    782 
    783         return DataFrame._read_parquet(
--> 784             source_prep, columns=columns, n_rows=n_rows, parallel=parallel
    785         )
    786 

~/work/dsengines/.venv/lib/python3.7/site-packages/polars/internals/frame.py in _read_parquet(file, columns, n_rows, parallel)
    580 
    581             if columns is None:
--> 582                 return scan.collect()
    583             elif is_str_sequence(columns, False):
    584                 return scan.select(columns).collect()

~/work/dsengines/.venv/lib/python3.7/site-packages/polars/internals/lazy_frame.py in collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache, no_optimization, slice_pushdown)
    351             slice_pushdown,
    352         )
--> 353         return pli.wrap_df(ldf.collect())
    354 
    355     def fetch(

RuntimeError: Any(ArrowError(NotYetImplemented("Decoding \"RleDictionary\"-encoded, dictionary-encoded optional V1 pages is not yet implemented for primitive")))
```

#### What is the expected behavior?

Without reading in columns that have lists as value, there is no error. I expected the same when reading in columns that have lists as value

**Comment by ddutt** [comment]
For a workaround, I use pl.from_arrow, but the performance clearly suffers

**Comment by ritchie46** [comment]
Nested types are not yet implemented in arrow2's parquet reader. You will need to use pyarrow until then.

**Comment by jorgecarleitao** [comment]
Do you know how the file was generated? Do you have a way to reproduce how to generate said file? We should be able to support that use-case. We need to extend the code [here](https://github.com/jorgecarleitao/arrow2/blob/main/src/io/parquet/read/primitive/nested.rs#L124) to read dictionary-encoded values on nested types.

**Comment by jorgecarleitao** [comment]
Awesome. I see you are using pyarrow.

Could you share a minimal example using `pyarrow.parquet` that generates a file that is un-readable by polars/arrow2? This way when we implement the decoder, we can use that snipped to ensure compatibility.

**Comment by ddutt** [comment]
@jorgecarleitao I'll provide such a data in a day or two, is that OK? Did you need it sooner? Thank you for jumping in on this. Any idea when it'll be ready?

**Comment by ritchie46** [comment]
@ddutt any news on this?

**Comment by zundertj** [comment]
The problem still exists on 0.13.12:

```python
import polars as pl
import requests
from io import BytesIO

url = "https://github.com/netenglabs/suzieq/blob/master/tests/data/nxos/parquet-out/routes/sqvers=2.0/namespace=nxos/hostname=dcedge01/ae4052489ad24989b6bee9944721d4e8.parquet?raw=true"
response = requests.get(url)
image_data = BytesIO(response.content)

df = pl.read_parquet(image_data)
```

which results in the same error as above:
```
exceptions.ArrowErrorException: NotYetImplemented("Decoding \"RleDictionary\"-encoded optional any pages is not yet implemented for Binary")
```

**Comment by ritchie46** [comment]
Thanks @zundertj. I will take that example upstream in arrow2.

**Comment by cjermain** [comment]
I'm running into related problems of nested structures. Here is a basic example:
```python
import pandas as pd
import polars as pl

# Write out a nested example
data = [                                                                                                       
    {'a': [{'b': 0}]},                                                                                         
    {'a': [{'b': 1}, {'b': 2}]},                                                                               
]
pd.DataFrame(data).to_parquet("~/test.parquet")

# Read it in polars
df = pl.read_parquet("~/test.parquet", use_pyarrow=True)
```
This fails in the Rust code with a `PanicException`:

```
```

**Comment by thobai** [comment]
I guess I have a problem related to this issue. I'm trying to serialize and deserialize a column with a list of type Categorical on version 0.13.40. Example code to reproduce the issue:

```
df = pl.DataFrame(
    {
        'str': ['A', 'B', 'A', 'B', 'C'],
        'group': [1,1,2,1,2]
    }
).lazy()
df = df.with_column(pl.col('str').cast(pl.Categorical))

df_groups = df.groupby('group').agg([pl.col('str').list().alias('strList')])
df_groups.collect().write_parquet('test.parquet')
df_groups_import = pl.scan_parquet('test.parquet').collect()
```

This returns `PanicException: not yet implemented: Dictionary(UInt32, LargeUtf8, false)`

**Comment by thobai** [comment]
@ddutt You mentioned that for your initial problem you used `pl.from_arrow` as a workaround. Did you use pyarrow to read the parquet for the workaround or did you use anything else?

For the problem that I posted above, pyarrow unfortunately is also not able to read the parquet file. It says `OSError: Unexpected end of stream`.

Did you use anything else or have another idea for a workaround? The only workaround that I found so far is using strings instead of categoricals, but that's also comes with quite a performance impact.

**Comment by ritchie46** [comment]
Could you confirm this has been fixed?

**Comment by thobai** [comment]
I just checked my specific problem on version `0.13.44` of the Python library and the problem remains. Do I need to rebuild from latest source?

**Comment by ritchie46** [comment]
`0.13.46` is latest. Could tou try updating?

**Comment by thobai** [comment]
ah, mixed up my environments. Retried with `0.13.36`, unfortunately with the almost the same result. It now says:
`ArrowErrorException: NotYetImplemented("Deserializing type Dictionary(UInt32, LargeUtf8, false) from parquet")`

**Comment by thobai** [comment]
I've created an issue on the arrow2 repository: https://github.com/jorgecarleitao/arrow2/issues/1091

**Comment by zundertj** [comment]
In 0.14.0, I can not reproduce https://github.com/pola-rs/polars/issues/2448#issuecomment-1143742488 any more, so closing this issue.
