### ISSUE TITLE
Silent conversion error on upcast from 'us' to 'ns' on datetime ingest from Arrow

### ISSUE THREAD

**Issue by alexander-beedie** [pola-rs/polars#2618]
#### Are you using Python or Rust?

Python, Windows 10, polars 0.12.24

#### Describe your bug.

Certain datetimes can be silently converted to values that are waaaay out on DataFrame init.

#### What are the steps to reproduce the behavior?

Create an Arrow table with the given datetime values, and load into polars:

```python
import polars as pl
import pyarrow as pa
from datetime import datetime, date

a = pa.Table.from_arrays(
    arrays=[ [datetime(2600,1,1,0,0,0,123456),datetime(2800,1,1,0,0,0,456789)],[128,256] ],
    schema=pa.schema( [
        ('timestamp', pa.timestamp('us')),
        ('value', pa.int16()),
    ] ),
)
# pyarrow.Table
# timestamp: timestamp[us]
# value: int16
# ----
# timestamp: [[2600-01-01 00:00:00.123456,2800-01-01 00:00:00.456789]]
# value: [[128,256]]

df = pl.from_arrow( a )

# ┌───────────────────────────────┬───────┐
# │ timestamp                     ┆ value │
# │ ---                           ┆ ---   │
# │ datetime[ns]                  ┆ i16   │
# ╞═══════════════════════════════╪═══════╡
# │ 2015-06-13 00:25:26.413904384 ┆ 128   │    <<< yikes
# ├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
# │ 2215-06-13 00:25:26.747237384 ┆ 256   │    <<< (and again ;)
# └───────────────────────────────┴───────┘
```

#### What is the expected behavior?

Either datetime values that match the original, or possibly (depending on `ns` precision datetime min/max bounds) an out of range error should be raised. In the example above, the resulting datetime values are hundreds of years off.

**Comment by ritchie46** [comment]
Thanks. I will fix it.

**Comment by ritchie46** [comment]
Ok, the issue is that we overflow `i64` when converting to `nanoseconds` because this is out of bounds for the`nanoseconds`. 

I do agree with you point that `us` is more valuable than `ms` as with `us` we get until the year `292434`, which should be sufficient. 

I will do the refactor from `ms` to `us` on a later point as this likely breaks stuff and I need some time for this.

**Comment by slonik-az** [comment]
I do not think that `us` is more valuable as default than `ms`. For example, Javascript uses `ms` as default and polars support Javascript bindings alongside Python.

Here is my reply in the previous issue on the same topic:
https://github.com/pola-rs/polars/issues/2616#issuecomment-1037227058

> I think that current design with `ms` as default and `ns` for extra precision (at the cost of reduced time span) makes a lot of sense. Polars is a Rust library first with bindings to Python and Javascript and possibly more languages in the future. Rust `std::time` has `ns` resolution, Python - `us` and Javascript - `ms`. Any hard choice will make someone unhappy. Milliseconds provide reasonable time resolution for most of datasets and nanoseconds are there for special cases when enchanted precision is needed.
> 
> EDIT: Pandas is another example that choose to deviate from native Python time resolution. Pandas has fixed `ns` for Timestamp and seems to interoperate with Python datetime just fine.

**Comment by ritchie46** [comment]
Fixed. :+1: I will see if we can reduce compile times a bit more and decide later if I maybe drop a time-unit.

**Comment by alexander-beedie** [comment]
> Any hard choice will make someone unhappy. 

If it was an either/or scenario, probably true - however, you don't really lose anything for the JS `ms` case by having `us`, as you still get _hundreds of thousands of years_ of lossless precision (for both units). In contrast, having only `ms` and `ns` restricts you to a 500 year window of lossless precision (for `us` and `ns`), which ends only ~140 years from now. That's quite a difference in effective constraints.

@ritchie46 : as always, thx for the updates/fixes :)
