### ISSUE TITLE
polar read parquet  fail

### ISSUE THREAD

**Issue by zhouchengcom** [pola-rs/polars#2641]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.13.1

#### What operating system are you using polars on?

Linux xsj 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

#### Describe your bug.

pl.read_parquet returns a RuntimeError.

#### What are the steps to reproduce the behavior?

```python
import polars as pl


pl.read_parquet("kk.parquet")
```

[kk.zip](https://github.com/pola-rs/polars/files/8059526/kk.zip)

#### What is the actual behavior?

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /github/home/.cargo/git/checkouts/arrow2-8a2ad61d97265680/394a699/src/io/parquet/read/dictionary.rs:222:26
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /github/home/.cargo/git/checkouts/arrow2-8a2ad61d97265680/394a699/src/io/parquet/read/dictionary.rs:222:26
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /github/home/.cargo/git/checkouts/arrow2-8a2ad61d97265680/394a699/src/io/parquet/read/dictionary.rs:222:26
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'internal error: entered unreachable codeinternal error: entered unreachable code', ', /github/home/.cargo/git/checkouts/arrow2-8a2ad61d97265680/394a699/src/io/parquet/read/dictionary.rs/github/home/.cargo/git/checkouts/arrow2-8a2ad61d97265680/394a699/src/io/parquet/read/dictionary.rs::222222::2626

stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    pl.read_parquet("kk.parquet")
  File "/root/.cache/pypoetry/virtualenvs/rlbl-NeUXV2HR-py3.8/lib/python3.8/site-packages/polars/io.py", line 871, in read_parquet
    return DataFrame._read_parquet(
  File "/root/.cache/pypoetry/virtualenvs/rlbl-NeUXV2HR-py3.8/lib/python3.8/site-packages/polars/internals/frame.py", line 537, in _read_parquet
    self._df = PyDataFrame.read_parquet(
pyo3_runtime.PanicException: internal error: entered unreachable code
```

**Comment by ghuls** [comment]
Does it work with pyarrow?
```
pl.read_parquet(, use_pyarrow=True)
```

@jorgecarleitao Is this fixed by: https://github.com/jorgecarleitao/arrow2/commit/394a699c106651c7b79d4cc62bb8d258c60d3911

**Comment by jorgecarleitao** [comment]
Yes, it was fixed on that one :) Sorry for that :(

**Comment by ghuls** [comment]
@jorgecarleitao The parquet file attached in the first post still fails with the latest arrow2 commit:
```python
In [3]: pl.read_parquet('/home/userDownloads/kk.parquet')
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /home/user.cargo/git/checkouts/arrow2-8a2ad61d97265680/9e6924b/src/io/parquet/read/dictionary.rs:222:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /home/user.cargo/git/checkouts/arrow2-8a2ad61d97265680/9e6924b/src/io/parquet/read/dictionary.rs:222:26
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /home/user.cargo/git/checkouts/arrow2-8a2ad61d97265680/9e6924b/src/io/parquet/read/dictionary.rs:222:26
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /home/user.cargo/git/checkouts/arrow2-8a2ad61d97265680/9e6924b/src/io/parquet/read/dictionary.rs:222:26
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /home/user.cargo/git/checkouts/arrow2-8a2ad61d97265680/9e6924b/src/io/parquet/read/dictionary.rs:222:26
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-3-4183cb8fe0ef> in <module>
----> 1 pl.read_parquet('/home/userDownloads/kk.parquet')

~/software/polars/py-polars/polars/io.py in read_parquet(source, columns, n_rows, use_pyarrow, memory_map, storage_options, parallel, row_count_name, row_count_offset, **kwargs)
    869             )
    870
--> 871         return DataFrame._read_parquet(
    872             source_prep,
    873             columns=columns,

~/software/polars/py-polars/polars/internals/frame.py in _read_parquet(file, columns, n_rows, parallel, row_count_name, row_count_offset)
    535         projection, columns = handle_projection_columns(columns)
    536         self = DataFrame.__new__(DataFrame)
--> 537         self._df = PyDataFrame.read_parquet(
    538             file,
    539             columns,

PanicException: internal error: entered unreachable code
```

**Comment by ghuls** [comment]
The parquet file has quite a number of rows (reading with pyarrow):
```python
In [3]: pl.read_parquet('/home/luna.kuleuven.be/u0079808/Downloads/kk.parquet', parallel=False, use_pyarrow=True)

Out[3]:
shape: (199999999, 9)
┌────────────┬─────────┬─────────┬─────────┬─────┬───────┬─────────────┬───────────┬────────┐
│ time       ┆ type    ┆ result  ┆ subtype ┆ ... ┆ count ┆ respondtime ┆ exception ┆ parent │
│ ---        ┆ ---     ┆ ---     ┆ ---     ┆     ┆ ---   ┆ ---         ┆ ---       ┆ ---    │
│ i64        ┆ cat     ┆ cat     ┆ cat     ┆     ┆ u16   ┆ u16         ┆ str       ┆ cat    │
╞════════════╪═════════╪═════════╪═════════╪═════╪═══════╪═════════════╪═══════════╪════════╡
│ 1642678630 ┆ request ┆ success ┆ sum     ┆ ... ┆ 1     ┆ 0           ┆ null      ┆ -      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1642678631 ┆ request ┆ success ┆ sum     ┆ ... ┆ 1     ┆ 0           ┆ null      ┆ -      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1642678631 ┆ request ┆ success ┆ get     ┆ ... ┆ 1     ┆ 0           ┆ null      ┆ -      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1642678631 ┆ request ┆ success ┆ get     ┆ ... ┆ 1     ┆ 57          ┆ null      ┆ -      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...     ┆ ...     ┆ ...     ┆ ... ┆ ...   ┆ ...         ┆ ...       ┆ ...    │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1642681682 ┆ request ┆ success ┆ get     ┆ ... ┆ 1     ┆ 0           ┆ null      ┆ -      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1642681682 ┆ request ┆ success ┆ get     ┆ ... ┆ 1     ┆ 0           ┆ null      ┆ -      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1642681682 ┆ request ┆ success ┆ get     ┆ ... ┆ 1     ┆ 0           ┆ null      ┆ -      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1642681682 ┆ request ┆ success ┆ get     ┆ ... ┆ 1     ┆ 0           ┆ null      ┆ -      │
└────────────┴─────────┴─────────┴─────────┴─────┴───────┴─────────────┴───────────┴────────┘
```

**Comment by jorgecarleitao** [comment]
You are right, this is something else; sorry for the noise. I have a PR here that I believe addresses this: https://github.com/jorgecarleitao/arrow2/pull/836  . I am trying to create a small repro with pyarrow to have it as parts of the tests

**Comment by ritchie46** [comment]
Fixed and released
