### ISSUE TITLE
Slicing Series with negative step size results in Error

### ISSUE THREAD

**Issue by slonik-az** [pola-rs/polars#3759]
#### What language are you using?
**Python**

#### Have you tried latest version of polars?
- [yes]

#### What version of polars are you using?
`polars-v0.13.49`

#### What operating system are you using polars on?
MacOS-12.4 (Monterey), MacBookPro M1 Max (Apple Silicon)

#### What language version are you using
`python-3.10.4`

#### Describe your bug.
Slicing with negative step sizes works fine for Polars DataFrames but fails for **Series**.

#### What are the steps to reproduce the behavior?
Here is MWE

```python
import polars as pl
import numpy as np
sr = pl.Series('', np.arange(5))
sr[::-1]
```

#### What is the actual behavior?
```
OverflowError                             Traceback (most recent call last)
File ~/pg/2/pl-01.py:5, in <module>
      2 import numpy as np
      4 sr = pl.Series('', np.arange(5))
----> 5 sr[::-1]

File /opt/pkg/mambaforge/envs/e310/lib/python3.10/site-packages/polars/internals/series.py:488, in Series.__getitem__(self, item)
    486 if isinstance(item, slice):
    487     start, stop, stride = item.indices(self.len())
--> 488     out = self.slice(start, stop - start)
    489     if stride != 1:
    490         return out.take_every(stride)

File /opt/pkg/mambaforge/envs/e310/lib/python3.10/site-packages/polars/internals/series.py:1251, in Series.slice(self, offset, length)
   1228 def slice(self, offset: int, length: int) -> "Series":
   1229     """
   1230     Get a slice of this Series.
   1231 
   (...)
   1249 
   1250     """
-> 1251     return wrap_s(self._s.slice(offset, length))

OverflowError: can't convert negative int to unsigned
```

#### What is the expected behavior?
Return a slice with negative step size like Dataframe slicing does. Behavior of a Series should be consistent with the behavior of a Dataframe whenever possible.

**Comment by ritchie46** [comment]
Thanks for the issue report. Do you mind making a PR for this one? It is all python.

**Comment by slonik-az** [comment]
I will try

**Comment by alexander-beedie** [comment]
@slonik-az @ritchie46: I took a look at this; it needed 2-3 lines in Rust to do efficiently, as `Series` doesn't actually expose `reverse` on its API yet (I've added it). Also, looks like `DataFrame` _only_ handles the `[::-1]` case, not negative strides in general. (I didn't actually realise this until I solved the general case for `Series` - I can port the same logic over to `DataFrame` while I'm at it ;) 

Shouldn't take much longer; expect it'll be ready to land sometime tomorrow evening (22nd), once I've had a chance to write tests and more pro-actively check edge cases. But, so far it's looking pretty solid, and is correctly handling weird slices like `[-1:-5:-2]` while matching the equivalent slice of a python list.

**Comment by ritchie46** [comment]
> ut, so far it's looking pretty solid and is correctly handling weird slices like [-1:-5:-2] while matching the equivalent 

What does this slice even do?

**Comment by alexander-beedie** [comment]
> > But, so far it's looking pretty solid and is correctly handling weird slices like [-1:-5:-2] while matching the equivalent
> 
> What does this slice even do?

Walk through the array/collection, starting at the last element `-1`, finishing at (but not including) the element fifth from the back `-5`, taking every second value `-2` as you go.  ;)
```python
>>> [0,1,2,3,4,5][-1:-5:-2]
[5, 3]
```

**Comment by alexander-beedie** [comment]
Update: will finish at the weekend - scope creep (but worthwhile ;)

**Comment by ritchie46** [comment]
fixed and merged. Thanks @alexander-beedie :+1:

**Comment by alexander-beedie** [comment]
> fixed and merged. Thanks @alexander-beedie 👍

Ah, the patch that was just merged doesn't actually fix this - the proper fix is coming later this weekend  :)

**Comment by ritchie46** [comment]
Ah.. :)

**Comment by alexander-beedie** [comment]
It all got a bit out of hand, hence the delay - rather than just "make the negative slice `[::-1]` work on Series", it becomes "make all slicing work on everything" :sweat_smile:
