### ISSUE TITLE
Allow regular expressions in individual items of list passed to pl.col([...])

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#7989]
### Problem description

Polars allows a regular expression argument to `pl.col` as follows:

```python
import polars as pl

df = pl.DataFrame({
    "a1": [1, 2, 3],
    "a2": [1, 2, 3],
    "b1": [1, 2, 3],
    "c1": [1, 2, 3]
})

df.select(pl.col("^(a|b).*$"))
shape: (3, 3)
┌─────┬─────┬─────┐
│ a1  ┆ a2  ┆ b1  │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 1   │
│ 2   ┆ 2   ┆ 2   │
│ 3   ┆ 3   ┆ 3   │
└─────┴─────┴─────┘
```

However, regex fails when `pl.col()` is supplied a list, and any of them are regular expressions. This can easily be worked around by simply adding your column names to the regular expression, but it's messy and IMO would be much cleaner if individual list items could be regular expressions.

### Feature Request: add regex support for individual list items

```python
df.select(pl.col(["^a.*$", "^b.*$"]))
```
Current behavior:
```
exceptions.ColumnNotFoundError: ^a.*$
```

**Comment by avimallu** [comment]
There are a bunch of issues raised recently around this - I think it should be grouped into another consistency thread like #6451:

#7818 ColumnNotFoundError when pass positional arguments or list of name with a regex
#7081 `Expr.exclude` should work on all multi-column expressions
#7753 Allow use of regex in `df.drop()`
#5418 Move regex-based column selection to a different method, or put it behind a keyword

**Comment by mcrumiller** [comment]
Resolved via #9204

**Comment by stevenlis** [comment]
@mcrumiller I'm confused. Is this resolved or am I having a regression? With `0.18.9`, I'm still having issue of https://github.com/pola-rs/polars/issues/7818

**Comment by mcrumiller** [comment]
@stevenlis I labeled it resolved because the `selectors` module implements the desired behavior. The original issue still technically exists I suppose.
