### ISSUE TITLE
Untraceable warning - argument is not explicitly sorted

### ISSUE THREAD

**Issue by 2-5** [pola-rs/polars#8476]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I get this warning in the output, but without any indication of what user operation caused it:

```
argument is not explicitly sorted

- If your data is ALREADY sorted, set the sorted flag with: '.set_sorted()'.
- If your data is NOT sorted, sort the 'expr/series/column' first.

This might become an error in a future version.
```

Since it's a large applications with many Polars calls, I had to clone the Polars repository and grep through the source code to figure out that it's probably caused by one of these operations: `groupby_rolling`, `groupby_dynamic` or some form of `asof`.

The warning only appears when running the code in the terminal, it doesn't appear if running in a Jupyter notebook in VS Code which is not ideal.

### Reproducible example

```python
-
```

### Expected behavior

More information about what Polars operation invoked by the user caused this. Ideally a Python `DeprecationWarning` is raised instead of `stderr` output.

### Installed versions

<details>

```
---Version info---
Polars: 0.17.8
Index type: UInt32
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: 2023.1.0
matplotlib: 3.7.1
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

**Comment by ritchie46** [comment]
Hmm.. I understand this is annoying. We cannot raise python warnings from our rust side and we only have this information during execution.

Were you able to solve the issue? Maybe we should revert that warning and raise an error on the 0.18 release?

**Comment by stinodego** [comment]
Here is a minimal reproduction:

```python
import polars as pl

lf = pl.LazyFrame(
    schema={
        "store_id": pl.UInt16,
        "item_id": pl.UInt32,
        "timestamp": pl.Datetime,
    }
).sort("timestamp")

lf.join_asof(
    lf,
    by=["store_id", "item_id"],
    on="timestamp",
    strategy="forward",
).collect()

```

**Comment by ritchie46** [comment]
Thanks! Will fix that one.

**Comment by 2-5** [comment]
> We cannot raise python warnings from our rust side

I don't know how the interop operates, but maybe there is a context object where you can record that a warning was issued and this context flag could be checked on return to the Python side.

> Maybe we should revert that warning and raise an error on the 0.18 release?

This feels like a bigger question. Should Polars allow "unsafe" operations (requiring sorted but not checking)? I think there are a few operations like that. Raising an error feels like the correct thing to do, especially since you can call `set_sorted` if you want to force the unsafe behavior.

> Were you able to solve the issue?

Yes, I was able to locate the operation by adding `print` in front of every invocation of `join_asof`.

I also had something like this before the `join_asof`, it doesn't raise, yet the warning is issued:

```python
assert df.get_column("index").is_sorted()
```

Maybe `Expr.is_sorted()` should set the `set_sorted` flag if it returns `True`?

**Comment by ritchie46** [comment]
> This feels like a bigger question. Should Polars allow "unsafe" operations (requiring sorted but not checking)?

It is not unsafe, but is it is not sorted, the output is incorrect. We will not corrupt your memory or something like that. ;)

I think that's a mistake on our side. That `set_sorted` should fix it. I shall issue a patch tomorrow or the day after. Sorry for the inconvenience :(

**Comment by 2-5** [comment]
Right, I meant "unsafe" in an extended way, including unexpected results.

The issue that really bothers me is that I didn't see the stderr warnings in Jupyter notebooks running in VS Code.

It seems VS Code (or maybe Jupyter) installs a `sys.stderr` redirector, but this doesn't catch Rust output:

```python
import sys

sys.stderr.write("bla\n")
# visible in notebook

sys.__stderr__.write("bla\n")
# original process stderr, not visible in notebook

sys.stderr
# <ipykernel.iostream.OutStream at 0x1e35a328d00>

sys.__stderr__
# <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
```

Obviously this is not Rust's fault yet it is the current status.

**Comment by radugrosu** [comment]
The funny thing is, my code also started producing this warning, and I use none of `groupby_rolling`, `_dynamic` or `asof` :confused: .

**Comment by stinodego** [comment]
Apparently `hist` did also produce the same warning.

**Comment by ritchie46** [comment]
> Apparently `hist` did also produce the same warning - maybe you were using that?

And `cut`. Both are fixed.

**Comment by radugrosu** [comment]
It _was_ `cut`. Thanks!

**Comment by stinodego** [comment]
Looks like this was not fixed properly. On Polars `0.17.10`, my repro example still erroneously shows the logging message:

```python
import polars as pl

print(pl.__version__)

lf = pl.LazyFrame(
    schema={
        "store_id": pl.UInt16,
        "item_id": pl.UInt32,
        "timestamp": pl.Datetime,
    }
).sort("timestamp")

lf.join_asof(lf, on="timestamp").collect()
```
@ritchie46 Could you look into this?
