### ISSUE TITLE
docs.rs isn't building latest polars-lazy crate

### ISSUE THREAD

**Issue by itamarst** [pola-rs/polars#9957]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

https://docs.rs/crate/polars-lazy/0.31.1

### Issue description

The API docs on docs.rs aren't building for newer versions of `polars-lazy`. See https://docs.rs/crate/polars-lazy/0.31.1/builds/861915 for example of why.

### Expected behavior

API docs available for latest version.

### Installed versions

N/A

**Comment by ritchie46** [comment]
Right, can do a patch release soon!

**Comment by lfn3** [comment]
I think this has been fixed - I can no longer repro it using `cargo +nightly-2023-07-14 rustdoc --all-features -Z unstable-options` on current main, while it fails on the tag `rs-0.31.1`

**Comment by lorepozo** [comment]
It's still broken in `0.32.1` though the failure is different: https://docs.rs/crate/polars-lazy/0.32.1 — here's the build failure: https://docs.rs/crate/polars-lazy/0.32.1/builds/886312

```
[INFO] [stderr] error[E0432]: unresolved import `jsonpath_lib::PathCompiled`
[INFO] [stderr]  --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/polars-ops-0.32.1/src/chunked_array/strings/json_path.rs:3:5
[INFO] [stderr]   |
[INFO] [stderr] 3 | use jsonpath_lib::PathCompiled;
[INFO] [stderr]   |     ^^^^^^^^^^^^^^------------
[INFO] [stderr]   |     |             |
[INFO] [stderr]   |     |             help: a similar name exists in the module: `Compiled`
[INFO] [stderr]   |     no `PathCompiled` in the root
```

The fix should involve updating [`make doctest`](https://github.com/pola-rs/polars/blob/main/crates/Makefile#L80) to catch such issues. I'm not able to reproduce this failure.

**Comment by stinodego** [comment]
Seems to be fixed now:
https://docs.rs/polars-lazy/0.35.2/polars_lazy/
